<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal Universitas_asalUniversitas</name>
   <tag></tag>
   <elementGuidId>1e90efc6-a43e-45d0-8bdf-7c743a33999c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='asalUniversitas0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asalUniversitas0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe097ee1-c9ac-463e-bfb1-bdfee86fa7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb221b3c-4640-421a-aa58-7fa2ef9bc3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>6974a276-034d-40e4-bd89-ff829d67a974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asalUniversitas0</value>
      <webElementGuid>9099ac00-465f-4fa3-a008-9eae9a0396ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asalUniversitas</value>
      <webElementGuid>01a9fb2c-bb09-4c4b-beac-ec32706a2c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Universitas</value>
      <webElementGuid>bb392452-c495-4a47-88e1-423ebd442050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asalUniversitas0&quot;)</value>
      <webElementGuid>2e2d1365-f0bc-4a7c-8770-99cc557e8586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='asalUniversitas0']</value>
      <webElementGuid>20714946-1ca5-49ff-855f-b475f70d594c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div/input</value>
      <webElementGuid>3c5ca55a-0662-4bec-bf71-de5426f8d82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asal Universitas'])[1]/following::input[1]</value>
      <webElementGuid>5f0cdb1a-1223-4c03-910a-190bd89378fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Akademik'])[1]/following::input[1]</value>
      <webElementGuid>96d46d09-e45b-4568-94bb-66221ad4f2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenjang Pendidikan'])[1]/preceding::input[1]</value>
      <webElementGuid>a3c41e1b-a07c-4654-978a-dfb005c42e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Masuk Universitas'])[1]/preceding::input[2]</value>
      <webElementGuid>3bbde14f-ec85-4c6b-abec-82ef3b04ce4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>37a640a5-f5a8-4b26-8153-daf2d108ddef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'asalUniversitas0' and @name = 'asalUniversitas' and @placeholder = 'Universitas']</value>
      <webElementGuid>e6dbe9b1-967b-4f9a-aa77-b683d5bd74e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
