<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahun Masuk Universitas_tahunMasuk</name>
   <tag></tag>
   <elementGuidId>6fc85e81-0203-4580-909b-76a2e60a088c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tahunMasuk0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tahunMasuk0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ad79b48-0123-4062-86c8-f05cadfc8d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbe30527-7f85-4f01-8bdc-06f78778a0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>790ec639-475f-4ec9-ac99-6ebfb35353eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tahunMasuk0</value>
      <webElementGuid>99b4aa1a-39f5-40d0-be83-6810b309aef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahunMasuk</value>
      <webElementGuid>e8a7e2ff-d993-480d-99dd-95ae5cebed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Masuk</value>
      <webElementGuid>d3f07b5a-2ffe-4e5c-b46e-a2602bfbbd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tahunMasuk0&quot;)</value>
      <webElementGuid>8fdf40f7-c283-44c1-b511-d9b2f1c1672c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tahunMasuk0']</value>
      <webElementGuid>b350bee8-7cf7-492b-83f8-3907b284ee9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>17a90a75-7fbf-43e4-8cb2-38ec79b1d536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Masuk Universitas'])[1]/following::input[1]</value>
      <webElementGuid>265398ce-24a5-4ba9-a076-5a11d10afbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenjang Pendidikan'])[1]/following::input[2]</value>
      <webElementGuid>ab902417-37af-4a9f-a058-f995db60312e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Tamat Universitas'])[1]/preceding::input[1]</value>
      <webElementGuid>a75079a1-b467-4b53-b6c3-6a26e512e1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Tambah Data'])[1]/preceding::input[2]</value>
      <webElementGuid>1dce6f2d-fa99-4337-813e-b01fc3834761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d595f563-ed30-47c2-a6a7-24c032aed6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tahunMasuk0' and @name = 'tahunMasuk' and @placeholder = 'Tahun Masuk']</value>
      <webElementGuid>984039be-e9f3-41d1-a1a6-bb60a17dd79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
