<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cairkan Dana</name>
   <tag></tag>
   <elementGuidId>a0f099a6-2abd-40f2-99c6-f73dd5829026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn__cairkan__dana.btn.btn-primary.text-white.w-100.fw-semibold.rounded-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4de823cc-ce5d-4c30-bbdd-06e3ab76dfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba5f6a8f-c80e-4a44-8ae6-e1ad031c98ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__cairkan__dana btn btn-primary text-white w-100 fw-semibold rounded-3</value>
      <webElementGuid>367507b3-99a1-436e-a331-93981eb2b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0b89b60f-1a55-487d-9443-1efe6f30c39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-alert-saldo-diproses</value>
      <webElementGuid>d8bb0e0b-3c64-415f-af01-b2a9152337ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cairkan Dana</value>
      <webElementGuid>f9d9d937-3def-431f-8b4e-4cdd64586b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-tarik-saldo&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-md&quot;]/div[@class=&quot;modal-content rounded-4&quot;]/div[@class=&quot;modal-body p-5 d-flex flex-column&quot;]/form[1]/div[@class=&quot;text-center px-3&quot;]/div[1]/button[@class=&quot;btn__cairkan__dana btn btn-primary text-white w-100 fw-semibold rounded-3&quot;]</value>
      <webElementGuid>066f5211-4370-4cf4-8e0d-b3dd3c6aebc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[3]</value>
      <webElementGuid>85364357-987d-4ea7-a318-f3e7f8dd587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tarik-saldo']/div/div/div/form/div[6]/div/button</value>
      <webElementGuid>1ff9c0f8-4030-427b-90e9-8a30a98a5350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 200.000-,'])[1]/following::button[1]</value>
      <webElementGuid>be72f761-1237-4e2a-989e-b562811c280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencairan Saldo'])[3]/following::button[1]</value>
      <webElementGuid>9a6b09fd-1b86-4f89-9d7b-0e80b3f1ebf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>e5ecda41-b28d-4000-94e1-7a7fc268c615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cairkan Dana' or . = 'Cairkan Dana')]</value>
      <webElementGuid>69032279-2aba-4821-abf0-b555dc19e092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
