<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pencairan Saldo_namaPenerima</name>
   <tag></tag>
   <elementGuidId>3eac573f-e35d-47c4-9ade-a4230aa1ff8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namaPenerima']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namaPenerima</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf1ffd4c-8955-489c-87e3-31613e0be685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f31611f-5d8d-4228-8b98-968f1930da3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fw-semibold border border-secondary px-3 rounded-3</value>
      <webElementGuid>70d1809b-1a09-4439-a811-f666f71f45bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaPenerima</value>
      <webElementGuid>8dd15439-c1ba-4e5c-8775-c66159632f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaPenerima</value>
      <webElementGuid>4487ca1c-ad7e-46db-9ebe-85ebbbaa1046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Nama Penerima</value>
      <webElementGuid>082822e1-bb0c-4c0a-b2af-6c0c15e0bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-tarik-saldo&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-md&quot;]/div[@class=&quot;modal-content rounded-4&quot;]/div[@class=&quot;modal-body p-5 d-flex flex-column&quot;]/form[1]/div[@class=&quot;nama__penerima mb-3 px-3&quot;]/input[@id=&quot;namaPenerima&quot;]</value>
      <webElementGuid>ba1f409c-7903-4bc0-8643-b40a55c82868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namaPenerima']</value>
      <webElementGuid>4be4444d-3f4f-4db2-852e-02e9bae68329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tarik-saldo']/div/div/div/form/div[2]/input</value>
      <webElementGuid>217bf7d3-e461-43f6-b994-6d5b9387eee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencairan Saldo'])[3]/following::input[1]</value>
      <webElementGuid>409b860e-7830-4202-adbd-d1efeb454102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencairan Dana Telah Diproses'])[1]/following::input[1]</value>
      <webElementGuid>5a4059f1-5757-4005-8c7b-42da714064cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 200.000-,'])[1]/preceding::input[2]</value>
      <webElementGuid>89a1e512-cce2-4ee4-a4d8-48b2e7599030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cairkan Dana'])[1]/preceding::input[2]</value>
      <webElementGuid>49d77ac0-e4ec-4a88-950c-bde8e31f784d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d2c7846a-beea-40f3-83f2-5d8527724784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'namaPenerima' and @name = 'namaPenerima' and @placeholder = 'Masukan Nama Penerima']</value>
      <webElementGuid>5f818b29-165d-436b-8d71-7f35755717c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
