<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mengatasi Kegilaan_epr-search</name>
   <tag></tag>
   <elementGuidId>dbce0ff5-2a9d-4d16-83f7-7d2612b3a12f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.epr-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b888663-fbe8-4f23-a4ac-2955724210fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Type to search for an emoji</value>
      <webElementGuid>bf77c347-6f3b-4649-9c75-3332f481fc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epr-search</value>
      <webElementGuid>f6dc7e32-922b-41fc-992d-a1cbf01d8410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea5d167a-12f7-430a-8eca-4117e65a314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>epr-search-id</value>
      <webElementGuid>65ea542d-a2ba-4561-9158-8274122af8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d31a0b4c-6844-45f3-baff-2b61d40feacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;body__chatbot d-flex justify-content-center my-5&quot;]/div[@class=&quot;wrapper__chatbot d-flex flex-column justify-content-between&quot;]/form[@class=&quot;input__chatbot bg-white d-flex py-2&quot;]/div[@class=&quot;emoji-picker bottom-0 left-0 w-50 container position-absolute z-3&quot;]/aside[@class=&quot;EmojiPickerReact epr-main&quot;]/div[@class=&quot;epr-header&quot;]/div[@class=&quot;Flex epr-header-overlay FlexRow&quot;]/div[@class=&quot;epr-search-container&quot;]/input[@class=&quot;epr-search&quot;]</value>
      <webElementGuid>4c5ce0c1-a4e8-416a-b91f-9b91910de241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>37495020-4723-4802-b9f4-1cca3a514bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/aside/div/div/div/input</value>
      <webElementGuid>93ae5e83-ec71-4c3a-924e-e409307d695e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>20875e86-6136-47de-899d-f11d75776957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>3152b4fc-40a9-41ef-9bd2-22a3e03e6580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
