<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar Sekarang</name>
   <tag></tag>
   <elementGuidId>98ed72da-3a0c-4e43-8e34-f16edd0a24f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.no-scroll-hover.btn-transparent.fw-bold.border.border-primary.text-primary.rounded-pill.my-3.px-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a14bbae-78c4-4365-9d50-43a3ca36dfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn no-scroll-hover btn-transparent fw-bold border border-primary text-primary rounded-pill my-3 px-4</value>
      <webElementGuid>de714ca2-be2b-4043-a8d6-b5dbc76d3948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1146f91a-6fd8-4caa-b0e0-5ce407ea0ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Sekarang</value>
      <webElementGuid>de39564c-29e2-4f4c-b674-82ae091e2b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offcanvasNavbar&quot;)/div[@class=&quot;offcanvas-body align-items-center&quot;]/a[1]/button[@class=&quot;btn no-scroll-hover btn-transparent fw-bold border border-primary text-primary rounded-pill my-3 px-4&quot;]</value>
      <webElementGuid>6db8cbdc-86d5-4e0f-be7e-b68fe20c3308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>6dbd0c70-8c5a-4a07-93ac-6e87599fd100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offcanvasNavbar']/div[2]/a/button</value>
      <webElementGuid>b4032c4c-df0a-4303-9b1a-b681ca4a37fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::button[1]</value>
      <webElementGuid>da61ee66-d0ae-4f6a-89b4-86991f964549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EmpathiCare'])[1]/following::button[2]</value>
      <webElementGuid>d6270c2b-34e0-47a2-8856-26dbb12a04ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sebagai Konselor'])[1]/preceding::button[1]</value>
      <webElementGuid>7d0e504a-9e41-43be-9941-a0624562227b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Sekarang']/parent::*</value>
      <webElementGuid>e5b3eb68-4ad7-4b55-856b-efa34623ff1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>956ecd7f-1193-4de5-8e17-6775bce1f1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Daftar Sekarang' or . = 'Daftar Sekarang')]</value>
      <webElementGuid>a8bd8498-2526-4f1b-8d00-7ca2fad6c664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
