<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Artikel</name>
   <tag></tag>
   <elementGuidId>ca3ed702-6ad4-413d-8b41-1882f3fac3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-artikel-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-artikel-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>806c38a5-85b9-48d9-b394-fd4c61663528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4bdeedc-2ab8-4c36-b2d7-70afab8ccb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-create border-primary artikel-background py-2 px-3 rounded-2 border-1 fw-bold</value>
      <webElementGuid>2aca4502-e9d4-4125-bd17-4207ecbd3838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-artikel-btn</value>
      <webElementGuid>90c405fd-361d-40b1-8a83-f28cab76e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Artikel</value>
      <webElementGuid>46519df6-0a10-4856-aab3-d16a660823d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-artikel-btn&quot;)</value>
      <webElementGuid>5231d580-1c6b-471b-8fa5-1ee15d0413b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-artikel-btn']</value>
      <webElementGuid>a8f44c3c-aa1f-4f60-af06-3960ecd91cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[2]/a/div/button</value>
      <webElementGuid>b2cf6294-0311-43db-ab79-3029734888e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Artikel'])[1]/following::button[1]</value>
      <webElementGuid>a6a521e5-ff4b-4576-bf58-f2312874fcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::button[1]</value>
      <webElementGuid>34638353-6cc6-475b-9b64-34af6667da07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'create-artikel-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>5404fa30-e9c7-49e4-a86f-774be33beb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/button</value>
      <webElementGuid>df7b7d01-eec0-4200-a992-5c656aa94c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'create-artikel-btn' and (text() = 'Tambah Artikel' or . = 'Tambah Artikel')]</value>
      <webElementGuid>1dc55d97-49a6-4b47-abaa-6ab8e7b2942f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
