<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tolak</name>
   <tag></tag>
   <elementGuidId>6876ddae-07d7-4d5b-ac87-08a8a2467e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-tolak-pasien&quot;]/div/div/div[2]/div[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-transparent.border-2.text-primary.border-primary.rounded-4.py-2.px-4.fw-semibold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d00bb255-50f2-4eeb-9b94-0c4b3e357b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bfbb3ce-e96f-4ec5-b9ca-a071fe2e802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent border-2 text-primary border-primary rounded-4 py-2 px-4 fw-semibold</value>
      <webElementGuid>8af3ce77-7e86-4367-9d65-86c5cae7fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>acac9953-b1ab-4536-9324-d04b5c885cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-tolak-pasien</value>
      <webElementGuid>890b0a61-6f6a-4196-8ceb-1e78106814fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tolak</value>
      <webElementGuid>9af345b1-e4b8-4ce2-8e18-035a74238e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-lihat-detail&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered  modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;ms-4&quot;]/div[@class=&quot;mt-5 d-flex flex-row gap-3&quot;]/div[2]/button[@class=&quot;btn btn-transparent border-2 text-primary border-primary rounded-4 py-2 px-4 fw-semibold&quot;]</value>
      <webElementGuid>7afd28a8-953c-4acb-b4bd-d90ee4861120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[11]</value>
      <webElementGuid>4c68bb7d-ba99-4a8f-b2f2-8ef19bda0227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-lihat-detail']/div/div/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>b5f30639-ca9c-4d4e-b4a8-b105fdb09bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima'])[1]/following::button[1]</value>
      <webElementGuid>bbfc1a61-1cf2-47a6-b3d2-f964cfd6e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoom'])[1]/following::button[2]</value>
      <webElementGuid>53a8bd47-1693-4cea-9810-e80b0c44f4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::button[1]</value>
      <webElementGuid>ccda55cc-696a-48cb-8f4b-37b7be8d6cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluhan'])[1]/preceding::button[1]</value>
      <webElementGuid>1ec4072c-bd6f-4959-a69d-e0624ebc4252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>49615c56-9682-4782-9e1c-a35968edda90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tolak' or . = 'Tolak')]</value>
      <webElementGuid>d55c6ca4-f771-4dc3-ac8e-b1d8b274bc55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
