<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Overbooking (1)</name>
   <tag></tag>
   <elementGuidId>2316b5ec-3176-4d7e-8202-40a07a46a48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.w-100.btn.border-secondary-subtle.text-black.fw-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ab5fcb0-feb1-4dd7-b563-c307ade5f1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e96ba3ba-30a5-4659-830b-8830d734c15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn border-secondary-subtle text-black fw-medium</value>
      <webElementGuid>6b2f339a-5277-452b-ac4c-2765c3217d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overbooking</value>
      <webElementGuid>f6deb31e-567b-4cdc-a1a6-0877b4d42168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-tolak-pasien&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row row-cols-lg-2 row-cols-1 g-2&quot;]/div[@class=&quot;col-12 col-md-6 col-lg-8&quot;]/div[1]/button[@class=&quot;w-100 btn border-secondary-subtle text-black fw-medium&quot;]</value>
      <webElementGuid>5d815694-bb94-490d-aada-fcba72aab6d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[3]</value>
      <webElementGuid>e538e07d-e91e-4d93-a640-43fd1bd815d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tolak-pasien']/div/div/div[2]/div[2]/div/div/button</value>
      <webElementGuid>3d9865e3-c165-4ac8-8c7c-c7f052d629ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Vidio Call'])[1]/following::button[2]</value>
      <webElementGuid>3c0bfbb8-3a4a-45af-aec1-028e84b903a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Chat'])[1]/following::button[2]</value>
      <webElementGuid>fa334bca-74ba-4aab-b45c-91af8d6cc8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterbatasan Waktu'])[1]/preceding::button[1]</value>
      <webElementGuid>045aadf2-740e-40d1-b44a-7c8e567f5fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter Ada Kegiatan Mendadak'])[1]/preceding::button[2]</value>
      <webElementGuid>f627a4a8-fa61-4660-900e-7db38ea452f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overbooking']/parent::*</value>
      <webElementGuid>3f416a80-710d-4358-bb60-9d27fbe2617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>fb017259-f92f-4178-8967-2232bdb32288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Overbooking' or . = 'Overbooking')]</value>
      <webElementGuid>8ce59f84-6cc4-4c8f-857c-73de254afe7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
