<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_X_- accept patient pop up</name>
   <tag></tag>
   <elementGuidId>20e689ef-6250-4aba-936d-872536080763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-terima-pasien&quot;]/div/div/div[1]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-terima-pasien > div.modal-dialog.modal-dialog-centered.modal-lg > div.modal-content > div.border-0.d-flex.justify-content-center.position-relative > div > button.btn-close.position-absolute.end-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2b1d850-cd75-4d55-b664-ee7874c94cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c01719f7-20ef-4c63-925f-c3fb62436627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close position-absolute end-0</value>
      <webElementGuid>ce69cf22-1998-4e67-a7c2-90b6c301a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>21c5a415-acde-4c12-bc9c-54fb5cbc12dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>8dbcc470-80e6-4f43-b7e0-2322f664a560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-terima-pasien&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;border-0 d-flex justify-content-center position-relative&quot;]/div[1]/button[@class=&quot;btn-close position-absolute end-0&quot;]</value>
      <webElementGuid>98789b83-1dc9-4379-b314-cf76315e2bc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[8]</value>
      <webElementGuid>9acc3923-6b85-435e-bb0e-f301675323d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-terima-pasien']/div/div/div/div/button</value>
      <webElementGuid>a7090d0d-499f-4b80-9348-0229d84e7488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>da868cce-3845-4d16-906d-7889720e4a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>dacc2f08-b464-490a-8c20-d117520894c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
