<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_X_popup reject pasient</name>
   <tag></tag>
   <elementGuidId>e9e14d7a-4075-4382-bcf1-d43bf9a90e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-tolak-pasien&quot;]/div/div/div[1]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-close.position-absolute.end-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eda2b1e0-dee5-44bd-ae9f-59d95cb0dd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>214484f1-8253-42b3-953b-d1d75d0dc623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close position-absolute end-0</value>
      <webElementGuid>f1453b34-40ed-4d79-9ce4-a9432cca13f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>0d4c6941-73e4-4740-a837-b0d3d5825f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9ef5a547-119a-4502-956a-cb1fcf5b0b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-tolak-pasien&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;border-0 d-flex justify-content-center position-relative&quot;]/div[1]/button[@class=&quot;btn-close position-absolute end-0&quot;]</value>
      <webElementGuid>09bc004f-4bd7-406d-b633-9720420e947e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[2]</value>
      <webElementGuid>eec9c22f-8641-47f4-a914-599b91b42b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tolak-pasien']/div/div/div/div/button</value>
      <webElementGuid>2e1fa8d3-6dca-40d7-84a4-f79a63a2ada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/div/div/div/button</value>
      <webElementGuid>4eb3d691-6fcf-4fc2-91e0-6656d1abd7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>401363a5-0e73-4803-8421-dae3f986afcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
