<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tolak_text-center</name>
   <tag></tag>
   <elementGuidId>c4d6d138-6bd4-4358-86de-6779183349f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-terima-pasien']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-terima-pasien > div.modal-dialog.modal-dialog-centered.modal-lg > div.modal-content > div.border-0.d-flex.justify-content-center.position-relative > img.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9305d15f-2c31-4c94-8eb7-7b0c08b90357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/iconAlertTerimaPasien-10f97fdf.svg</value>
      <webElementGuid>2d7c933b-afca-46d0-a384-bcfe7b201d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-alert</value>
      <webElementGuid>e5abbe19-644e-42bf-b265-65eeb609195f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>efc7f3aa-cddd-4710-bc09-3eac7364917c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-terima-pasien&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;border-0 d-flex justify-content-center position-relative&quot;]/img[@class=&quot;text-center&quot;]</value>
      <webElementGuid>367e9426-ee29-4f74-811f-037a257923fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-terima-pasien']/div/div/div/img</value>
      <webElementGuid>c9106c1c-1094-4457-8f98-2b8f5fbefa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon-alert'])[2]</value>
      <webElementGuid>9f168015-1f0e-4ee7-a66b-a487549b28fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>a8472714-6a8d-4f98-8821-2d9590cf24b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/iconAlertTerimaPasien-10f97fdf.svg' and @alt = 'icon-alert']</value>
      <webElementGuid>9b900e5f-7bce-4501-933c-7c39e085fb59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
