<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tuliskan alasan Penolakan_floating_7b3480 (1)</name>
   <tag></tag>
   <elementGuidId>d336eceb-dfee-44d1-b757-92b39daf126a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floatingTextarea2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='floatingTextarea2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d8539106-91c3-44df-a355-a8b0825de976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-100</value>
      <webElementGuid>b2b514f7-3883-4e1e-9720-79c9a71fd214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingTextarea2</value>
      <webElementGuid>4e0ea1f4-6490-4eaf-9aec-da43aaa51a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floatingTextarea2&quot;)</value>
      <webElementGuid>f7347a46-b522-41c6-a843-3fb3361fe84b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='floatingTextarea2']</value>
      <webElementGuid>f4bf8ae9-8718-4724-9955-183b9bf91b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tolak-pasien']/div/div/div[2]/div[3]/textarea</value>
      <webElementGuid>caa1f97e-8bf8-47f1-89fe-130ed2c1feda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>21752750-867f-4776-9c5c-d141e9f0d7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'floatingTextarea2']</value>
      <webElementGuid>74404519-5bbd-499b-b4ca-e29cd409a2e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
