<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomeServicesAbout UsDownload Sekarang</name>
   <tag></tag>
   <elementGuidId>bc8ae2c1-3c27-4e52-9321-5ba03250e6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNav']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navbarNav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af016355-e3aa-4995-98f6-b66b3a2112d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapse navbar-collapse</value>
      <webElementGuid>84fb0a52-891b-4373-ad1e-9ef57d8fc8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarNav</value>
      <webElementGuid>fb0a1cc2-242d-42c4-ae9d-2de4ae6a8fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeServicesAbout UsDownload Sekarang</value>
      <webElementGuid>1e67e297-dc83-4d0e-be00-c7e41c587b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNav&quot;)</value>
      <webElementGuid>2438f767-d5a9-4297-bc31-2055e5e80c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='navbarNav']</value>
      <webElementGuid>4a860690-4a03-4fb6-9882-cfb3c13b5d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div[3]</value>
      <webElementGuid>27bf5282-bd07-4ede-add7-dd12fc6e3aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>baacc043-14c9-49fb-9a96-552465ea0cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'navbarNav' and (text() = 'HomeServicesAbout UsDownload Sekarang' or . = 'HomeServicesAbout UsDownload Sekarang')]</value>
      <webElementGuid>a19d42c6-9678-4f3d-82f7-03faa2420a26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
