<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_bca</name>
   <tag></tag>
   <elementGuidId>85088e6b-4c00-4dae-9b34-199ff5c6b338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr[4]/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac86964a-7bd4-4262-a7bf-68c947f8b1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-decoration-none text-dark</value>
      <webElementGuid>56c243c2-7aaf-4e8c-8bf9-e4a027be1600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dokter/transaksi/otomatis/22</value>
      <webElementGuid>4e187706-b54d-47bc-ba33-0061da8c08bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bca</value>
      <webElementGuid>e83a9db7-c577-4960-a50b-a5476aeb63c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height p-row-odd&quot;]/td[6]/a[@class=&quot;text-decoration-none text-dark&quot;]</value>
      <webElementGuid>87fb28a5-c825-4714-8fa6-82038c186706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr[4]/td[6]/a</value>
      <webElementGuid>7edf6dec-f625-4e78-be96-6e2c179a6349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'bca')])[2]</value>
      <webElementGuid>f6bd2523-52e4-4ea2-bc85-dec2ec4c1c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Premium'])[2]/following::a[1]</value>
      <webElementGuid>b66c3fc8-5d0a-4634-bb03-4104df1867b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nurul fauziah'])[2]/following::a[1]</value>
      <webElementGuid>2111d21d-b82e-4d91-8f07-1d70a9bc3fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M-1702405614'])[1]/preceding::a[1]</value>
      <webElementGuid>e5310673-8e4d-4d3a-be3e-d222dc5aa0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Instan'])[3]/preceding::a[1]</value>
      <webElementGuid>89e9cbd4-9f78-4a44-85c5-28a9dc74ad28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/dokter/transaksi/otomatis/22')])[2]</value>
      <webElementGuid>44f62265-56c4-46e7-b4eb-f2431d0d57c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/a</value>
      <webElementGuid>7a439890-67e1-4418-be79-0f90ffb19610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dokter/transaksi/otomatis/22' and (text() = 'bca' or . = 'bca')]</value>
      <webElementGuid>2448963d-320a-482b-907f-68f98588642b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
