<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>85701732-5aa5-4e51-9bab-0a5341862616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fe89787-0dad-4257-9b9b-102d8e0c44ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e937beec-d807-4614-b247-9a90c3fa23e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bttn btn-secondary w-100 fw-bold 
              
            </value>
      <webElementGuid>7bb499ac-1de3-4e95-830d-460fd5fc00ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>b646fe0e-2e20-493d-a19c-05b1f2608228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>ca499c17-7eb0-4207-b9b2-a9dfb454a06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-submit&quot;)</value>
      <webElementGuid>837d7acd-f21f-4fbf-8517-fc6144619a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-submit']</value>
      <webElementGuid>959cfdf2-3a96-422e-8054-263e68ab8e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[6]/button</value>
      <webElementGuid>55cf9cd3-f381-48ca-b405-b3ea7bf092c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat saya?'])[1]/following::button[1]</value>
      <webElementGuid>54c165ce-1069-4165-a086-9a6cb2d8e16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::button[1]</value>
      <webElementGuid>10585079-c100-4872-9fdd-fea5110ce776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btn-submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d33ab20b-4b9b-4f0d-a4f7-fd72754e150d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7fee7fc6-5a1e-41f2-88c0-c919b05d0dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btn-submit' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>da95c53e-621f-4464-9bba-18d93bd25b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
