<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor SIP_noSip</name>
   <tag></tag>
   <elementGuidId>d004a4e5-bf47-41cd-82fc-86b9d30a58a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noSip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noSip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9320ea14-f192-4133-a8ee-38d08e76c53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d435d9fa-ae5a-4957-b628-09a5a0185c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>4ef74cb4-19c6-4bd4-b4b8-e476d036ad26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noSip</value>
      <webElementGuid>cf5ef6ed-91c3-4363-b26f-1fd54e361bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noSip</value>
      <webElementGuid>298a262d-373c-4658-872c-8c90ce207fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Surat Izin Praktik</value>
      <webElementGuid>6e3ed43e-c1f1-490b-8b7c-4a7c67c5d48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noSip&quot;)</value>
      <webElementGuid>93a9b4ee-9b1e-4502-aaae-b26b2da20da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noSip']</value>
      <webElementGuid>12484782-0f71-4354-9388-1a7db24da0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div[5]/div[2]/input</value>
      <webElementGuid>c05250cd-0f35-4457-9cd6-f13770e3e35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>dc1fda37-c022-418b-885d-050444be2c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'noSip' and @name = 'noSip' and @placeholder = 'Nomor Surat Izin Praktik']</value>
      <webElementGuid>cab20826-c080-4245-b97b-3d77b7e76b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
