<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provinsi_provinsi</name>
   <tag></tag>
   <elementGuidId>b264eb37-d2fa-4f4b-9f7d-5351ad495c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provinsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='provinsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afe3c428-4a80-49d0-9b2d-d1817f3f7ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f429fe9-3b33-4046-8409-2e9f896b6ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>9b93c810-1d95-453b-8f41-ed2da05ad360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provinsi</value>
      <webElementGuid>81efd6a2-9d70-43e7-ac38-382f3e5f799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provinsi</value>
      <webElementGuid>9fae0668-0dfd-4244-88ff-613366bed2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Provinsi</value>
      <webElementGuid>60f920b2-eea8-4554-96c8-a0f7fed1ec24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provinsi&quot;)</value>
      <webElementGuid>1c975f3f-c426-4b83-bc89-726267e1658e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='provinsi']</value>
      <webElementGuid>2cb4974c-16b5-4bd6-8c48-d4bf4e50a602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div[3]/div[2]/input</value>
      <webElementGuid>f2b1141e-e185-4192-bfad-0848d51f920b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>fd984a9c-c55f-4682-b4be-765084600dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'provinsi' and @name = 'provinsi' and @placeholder = 'Masukkan Provinsi']</value>
      <webElementGuid>38bedeb9-27d7-48f8-8947-7915d27e30f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
