<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_namaLengkap</name>
   <tag></tag>
   <elementGuidId>36a7213c-602d-414b-8c07-6bdaac447346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namaLengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namaLengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91c404e4-ae67-42af-90a4-33f0bd6eab95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6edf44e6-0a1d-40d0-ac1b-fbc3476d35b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>f555ddef-0c15-4cc5-8924-921fbb971e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaLengkap</value>
      <webElementGuid>b315056b-d8b3-465b-97e8-dff129cba81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaLengkap</value>
      <webElementGuid>cfeae783-5400-4dbe-a2a5-6a4462a625ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap</value>
      <webElementGuid>d57b1bd4-cef1-47a2-9f04-7f50e4471ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaLengkap&quot;)</value>
      <webElementGuid>a0e4861e-4b1c-4808-bacf-d9863d1809e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namaLengkap']</value>
      <webElementGuid>4f237d37-3f0d-44b7-933b-8390e75a310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div/div/input</value>
      <webElementGuid>f12ae3e6-ea66-4ed9-b008-a3c8a2f818d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>e4a89150-0d07-433b-988f-d319df5bf8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'namaLengkap' and @name = 'namaLengkap' and @placeholder = 'Nama Lengkap']</value>
      <webElementGuid>56cd77e4-522a-46b2-9c58-0ac0e5675967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
