<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Handphone_noHandphone</name>
   <tag></tag>
   <elementGuidId>bd431edd-d5d6-47f7-91de-2d340f53840e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noHandphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noHandphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26bf373a-e2bd-4b05-8991-d4fb160f3223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e582c3d-59ef-424c-af40-7bd0c6eba512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>023fbf6f-1698-4840-9ad7-de6efa4715a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noHandphone</value>
      <webElementGuid>13962fc0-24c6-4fa6-8547-7f20cc7314f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noHandphone</value>
      <webElementGuid>5f7b366e-3ff6-45b5-a4fa-8c4daac66a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Ponsel</value>
      <webElementGuid>0cfa8f8c-c4b2-4f7a-bae3-f7ae62f29468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noHandphone&quot;)</value>
      <webElementGuid>d93b8a04-0534-499e-834b-b1289ca8fcb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noHandphone']</value>
      <webElementGuid>145a827f-5d78-4b5c-a6c6-4ac209e9d610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>fcded8ef-6a83-4b8f-a353-bf861196e6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>a99163dc-6003-4bf0-bdee-60eb7cf03797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'noHandphone' and @name = 'noHandphone' and @placeholder = 'Nomor Ponsel']</value>
      <webElementGuid>b08e51ee-535a-4ed2-a693-7d4a23ce8447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
