<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor STR_str</name>
   <tag></tag>
   <elementGuidId>ca6cbdda-d2d6-4013-baf9-d6e8e11fb756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#str</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='str']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa46b118-8d14-49fb-a4dd-f5f22cc1e93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e58ed56-8c32-4505-8c11-5b3b927d26a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>204533f0-7bbf-4075-ad3a-5a75c97727d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>str</value>
      <webElementGuid>9fdfa355-674d-43d7-9338-91ad13dae971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str</value>
      <webElementGuid>6ef67897-adc5-4a27-a802-347d39d81b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Surat Tanda Registrasi</value>
      <webElementGuid>eb22426f-5325-4d94-8fe9-68470695ac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;str&quot;)</value>
      <webElementGuid>6b36c069-9260-4277-b35d-aa6522ff3f38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='str']</value>
      <webElementGuid>56d63569-5ecf-4e11-9a73-967aefd9e785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div[5]/div/input</value>
      <webElementGuid>ab0f18da-3685-4fc0-a334-462806203325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>52669836-5e3b-435e-92e8-694bd2e08c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'str' and @name = 'str' and @placeholder = 'Nomor Surat Tanda Registrasi']</value>
      <webElementGuid>2fd3ade4-1798-414b-9d2b-a94ebba7034e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
