<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KotaKabupaten_kotaKabupaten</name>
   <tag></tag>
   <elementGuidId>a753f79c-cf1f-4f4c-a363-e56a37fdf57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kotaKabupaten</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kotaKabupaten']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b39df5d1-9f4a-4693-843e-c5c6543a3019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f8a5e81-a092-43a1-bcf5-9ac7c6209fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>7f333295-4b65-4498-8dfb-de022fcbf976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kotaKabupaten</value>
      <webElementGuid>c825a0f5-05fc-4320-8f6b-6ea9b7105b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kotaKabupaten</value>
      <webElementGuid>aab83323-a3cb-433d-88ba-6f731ddd2e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kota/Kabupaten</value>
      <webElementGuid>8c7b81fe-ecf6-4f01-ab0d-00c34305ed74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kotaKabupaten&quot;)</value>
      <webElementGuid>ecc6d1f2-419d-4775-ad1a-eeb744d2e06a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kotaKabupaten']</value>
      <webElementGuid>c8ad5e93-2163-48e3-a85d-98db8e74659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div[4]/div[2]/input</value>
      <webElementGuid>9d6b08eb-00a9-4737-84d0-937a52740ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>0dfbcae3-f336-4cfa-beba-d95ef198bbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kotaKabupaten' and @name = 'kotaKabupaten' and @placeholder = 'Kota/Kabupaten']</value>
      <webElementGuid>964defba-c95d-4fa6-8072-d594be22d4d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
