<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Artikel</name>
   <tag></tag>
   <elementGuidId>7c7258c0-e1ba-462e-82e1-2df062ea7f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-artikel-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-artikel-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3cf5477-ceb7-4a89-9ef3-23a5015984c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f934e57a-c4fb-4ebb-8221-236d2a9cc549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-create border-primary artikel-background py-2 px-3 rounded-2 border-1 fw-bold</value>
      <webElementGuid>8a2c8958-0acb-4aef-9fc5-64d1ccb374a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-artikel-btn</value>
      <webElementGuid>aa43da30-ab62-4302-a827-34110cbd85d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Artikel</value>
      <webElementGuid>07861db7-f9b8-4f82-a68f-f43d46e8bf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-artikel-btn&quot;)</value>
      <webElementGuid>a51af68f-a281-468c-9734-829f0b44ad66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-artikel-btn']</value>
      <webElementGuid>b91e93b3-1b2f-4adc-a4d9-df0b95bc3989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[2]/a/div/button</value>
      <webElementGuid>9dab4b69-7a19-4c87-b167-ad0350c0b99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Artikel'])[1]/following::button[1]</value>
      <webElementGuid>9288ff8b-d009-4532-a60a-0d86520dc6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::button[1]</value>
      <webElementGuid>51eeab7f-ea21-4722-bec9-b3d120ba505f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'create-artikel-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>3258da29-ffa5-47c7-8289-0608b835e6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/button</value>
      <webElementGuid>010e22ad-3e57-4a6b-8a84-e74bc8155049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'create-artikel-btn' and (text() = 'Tambah Artikel' or . = 'Tambah Artikel')]</value>
      <webElementGuid>ae331e68-b3a4-4224-94d7-17252ac1c39f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
