<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah Artikel</name>
   <tag></tag>
   <elementGuidId>82ec7513-d42f-4e5c-ad24-47f115d25e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-upload-artikel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-upload-artikel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c909b512-6173-442a-9880-381705d32b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>330167cf-1726-43d4-a15e-bc1a7b77bb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary me-3 btn-upload-artikel fw-semibold</value>
      <webElementGuid>2e62b7a1-524c-4bc2-8932-a2a0d7500b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-upload-artikel</value>
      <webElementGuid>1490acb0-f121-4209-8a49-91219f6e4081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah Artikel</value>
      <webElementGuid>6aa34dab-9b31-4f51-a052-61577bd9d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-upload-artikel&quot;)</value>
      <webElementGuid>15a332f3-c6f6-4944-8456-dffaa2c83724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-upload-artikel']</value>
      <webElementGuid>17966595-42a1-45cd-a8a7-49540c723ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div/button</value>
      <webElementGuid>310f24e8-c115-411a-b379-5fb0a432baf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Artikel'])[1]/following::button[8]</value>
      <webElementGuid>9b093e6b-68e1-4423-aa48-779c5f50f1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::button[8]</value>
      <webElementGuid>a6103c5e-5451-4c01-a002-211c86b90484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan sebagai Draft'])[1]/preceding::button[1]</value>
      <webElementGuid>59bcc951-79a6-4080-ad0d-86b98903dfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilitas'])[1]/preceding::button[2]</value>
      <webElementGuid>946de05b-a8e0-4a84-ad12-d82ed58ac018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah Artikel']/parent::*</value>
      <webElementGuid>fdabaee2-8737-4435-89e9-0342bdecfcda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>3cc6dc1f-3952-4afe-9fc6-2978696744c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'button-upload-artikel' and (text() = 'Unggah Artikel' or . = 'Unggah Artikel')]</value>
      <webElementGuid>8f6f8d8e-efd7-4a59-bb06-0fbb6e38624b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
