<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan sebagai Draft</name>
   <tag></tag>
   <elementGuidId>887a7ee4-69ce-482e-8012-c3fadd4afe61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.me-3.btn-draft-artikel.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fba8689-2fa1-48ab-93b2-d696236d9eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1a25968-a2a8-4a0b-9394-39d965d92623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn me-3 btn-draft-artikel fw-semibold</value>
      <webElementGuid>a7e4ff0c-a64f-4c75-b6f4-e7ef7c773ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan sebagai Draft</value>
      <webElementGuid>3de126c3-3f2f-403b-9cda-274a016a7220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;d-flex m-3 button-form-artikel&quot;]/div[2]/div[1]/button[@class=&quot;btn me-3 btn-draft-artikel fw-semibold&quot;]</value>
      <webElementGuid>45d85cf9-5707-448b-ad1c-8ecc6532fdec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[2]</value>
      <webElementGuid>1a051994-c0cc-4ed4-b704-b5c7330414a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div[2]/div/button</value>
      <webElementGuid>adea7e5a-ed37-455f-85c3-5c547bd5f50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Artikel'])[1]/following::button[1]</value>
      <webElementGuid>fb48b135-7aba-4276-a0b1-817f5e57ca5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Artikel'])[1]/following::button[9]</value>
      <webElementGuid>ab874c06-6089-44a7-9a91-2e3c84cde5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilitas'])[1]/preceding::button[1]</value>
      <webElementGuid>653f9b8e-031a-4e6f-8be6-e0a6653df6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privat'])[1]/preceding::button[1]</value>
      <webElementGuid>b0dcd6f2-509c-4151-87b5-ec2798bbec63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan sebagai Draft']/parent::*</value>
      <webElementGuid>c6bfe7d7-52e0-4dd3-9260-a390851cd029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>cdb3bdfb-fb7f-4cff-b0a4-55bd47799297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Simpan sebagai Draft' or . = 'Simpan sebagai Draft')]</value>
      <webElementGuid>3731373d-196c-423a-a9d5-97aebaa72dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
