<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Artikel_link-video-artikel</name>
   <tag></tag>
   <elementGuidId>9351f486-631d-4724-8473-4757b8d90876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-video-artikel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link-video-artikel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb350ee4-9d0e-48bc-8262-f2315436d1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>018105b1-3165-42db-902e-f4969b375af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3 border-solid border-1</value>
      <webElementGuid>b9e936b9-4698-4e20-b634-af12b95cfbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-video-artikel</value>
      <webElementGuid>3ddcec1a-e898-4828-a123-67508175096b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link-video-artikel</value>
      <webElementGuid>00538992-6635-47db-86fa-db7e1838c283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-video-artikel&quot;)</value>
      <webElementGuid>2a86d243-fa84-43c2-8c6f-7fc24574077e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link-video-artikel']</value>
      <webElementGuid>fb3a62d0-22f7-4c8a-9a67-8ab25f4bf329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/input[2]</value>
      <webElementGuid>70fcd069-748d-458e-b13c-5b905623e265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>73eccd1c-822f-4985-b1a8-a7440a7e784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'link-video-artikel' and @name = 'link-video-artikel']</value>
      <webElementGuid>03d10816-4707-4691-a94d-e2585df60a72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
