<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dr. Helen_checkBox-artikel</name>
   <tag></tag>
   <elementGuidId>482bd391-bd36-494e-bd9d-5706ebab643a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBox-artikel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBox-artikel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24720e50-fc92-4200-bffb-8eae6ad76574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2524809e-e56a-413c-894b-9f250b9378ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBox-artikel</value>
      <webElementGuid>6ce99c16-6b46-41fa-aeb9-4b19e8155032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input border-2</value>
      <webElementGuid>1326df88-5992-4fe6-9cd0-2502183d9579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9c07c0b6-0539-4438-8c45-73ba53ca260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;container rounded-2 py-4&quot;]/div[1]/div[1]/div[@class=&quot;py-1&quot;]/div[@class=&quot;form-check&quot;]/input[@id=&quot;checkBox-artikel&quot;]</value>
      <webElementGuid>af361c1f-8542-45ff-bd6f-e8630ed06e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBox-artikel']</value>
      <webElementGuid>2212a293-2aca-4969-926e-c71dda740985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>49b04eac-007f-486c-a218-e455c43f013a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>6924bc2d-b4ed-41ea-b0ca-d4c23314be12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkBox-artikel']</value>
      <webElementGuid>431e9ced-a3df-499e-84da-3dc41e0276cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
