<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Publik</name>
   <tag></tag>
   <elementGuidId>c68359a9-0dd6-4c96-a161-652c4d45bbbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.m-0.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/div[2]/div/div/div/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c755f951-11e4-43a8-9457-7609509d3434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 text-primary</value>
      <webElementGuid>38acacab-0622-48d9-ba65-38a816a58d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publik</value>
      <webElementGuid>7a509d88-d1dc-43c5-8371-db1af5fbcd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;container  rounded-2 py-4 my-4&quot;]/div[1]/div[@class=&quot;grid&quot;]/div[@class=&quot;row justify-content-center align-items-center g-2 mb-2&quot;]/div[@class=&quot;col text-status text-end text-end pe-2&quot;]/div[@class=&quot;btn m-0 p-0&quot;]/button[@class=&quot;nav-link&quot;]/span[@class=&quot;m-0 text-primary&quot;]</value>
      <webElementGuid>a5374479-a8f2-44ca-98fb-cd0bda0a7777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[2]/div/div/div/div/div[2]/div/button/span</value>
      <webElementGuid>92ea5c3a-0fd2-4479-b326-709b463561f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilitas'])[1]/following::span[1]</value>
      <webElementGuid>02895624-4cda-4ce9-9727-9e9cfc070e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan sebagai Draft'])[1]/following::span[1]</value>
      <webElementGuid>c0a03277-0e79-4792-a635-dc220b3710de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publik'])[2]/preceding::span[1]</value>
      <webElementGuid>5633f565-73b6-4874-94b2-48f51bbc91cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privat'])[1]/preceding::span[1]</value>
      <webElementGuid>03bdc668-de7f-44a4-b02f-317504087ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publik']/parent::*</value>
      <webElementGuid>066f84a5-276c-4893-8310-6bb4db6a0f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/button/span</value>
      <webElementGuid>e7d7d128-ba1f-4684-9e01-39ba160ba725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Publik' or . = 'Publik')]</value>
      <webElementGuid>23a6dab0-ce23-4554-9756-e4fe13bf8b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
