<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan</name>
   <tag></tag>
   <elementGuidId>543bf9b0-ebdb-43a7-beb3-d4c91530ea16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div/div/div/div[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button-container.d-flex.justify-content-center.mb-3 > div > button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ba0e601-e791-49aa-97d0-7414732e84f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43da15dd-0d85-48e3-a42e-b1d711cd8354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>87db0dd8-7298-49d2-a782-98a4e2e72ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan Perubahan</value>
      <webElementGuid>f13612f7-ad3b-4c1a-a676-ede17e545ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/div[@class=&quot;pengalaman&quot;]/div[@class=&quot;container justify-content-center&quot;]/div[@class=&quot;button-container d-flex justify-content-center mb-3&quot;]/div[1]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>c5821813-a73d-4056-bfee-727ca49aab27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[3]</value>
      <webElementGuid>becb883a-a199-4c1c-b5fb-cccf1822774e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[4]/div/button</value>
      <webElementGuid>4b8fa970-9768-4bbe-8718-bbb4a45ed289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Tambah Data'])[1]/following::button[1]</value>
      <webElementGuid>e6693a50-52ce-4b23-b30b-3898e3d29e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[2]</value>
      <webElementGuid>3672f5d6-a49c-4dd2-aa34-97bb83d593a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin ingin menyimpan perubahan?'])[1]/preceding::button[1]</value>
      <webElementGuid>93394e79-7a69-4d39-b73e-bb26c5721de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan Perubahan'])[2]/preceding::button[1]</value>
      <webElementGuid>7c1e8ef6-efcf-4951-8af7-1a8f1b8413d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan Perubahan']/parent::*</value>
      <webElementGuid>ff9d8ac3-7c03-4b3e-a7f1-4358ebd0cbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>842d4eff-90bd-4618-b1e2-bafa80352668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Simpan Perubahan' or . = 'Simpan Perubahan')]</value>
      <webElementGuid>35a0524f-131f-46ec-86bd-3c81b07580ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
