<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Awal Bekerja_awalBekerja_1</name>
   <tag></tag>
   <elementGuidId>17b64236-ea5a-4dbc-a968-b3676f341be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#awalBekerja1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='awalBekerja1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3eb3345e-df7a-4bf6-8345-29ea76b0a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63196f75-38db-454e-9aa1-5d243033647f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>e4539e6f-181b-4f48-97b8-1a7138fbb89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>awalBekerja1</value>
      <webElementGuid>67035cf1-682f-4b04-8f35-87ea8dc8322b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awalBekerja</value>
      <webElementGuid>93e4476e-69c7-48e0-b39e-976d50bc2d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Masuk</value>
      <webElementGuid>f2401b64-c52c-4496-bee9-ad1836ec8b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awalBekerja1&quot;)</value>
      <webElementGuid>2ebb942c-f1b7-406c-b9ec-678dab54412c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='awalBekerja1']</value>
      <webElementGuid>03341408-518d-40ce-bd71-4793d27134ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form[2]/div[2]/div/input</value>
      <webElementGuid>7ee9804e-8ee9-4cfa-9aea-f7c4db7df151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div/input</value>
      <webElementGuid>727cbab5-4c3e-41ac-827c-67b97d860bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'awalBekerja1' and @name = 'awalBekerja' and @placeholder = 'Tahun Masuk']</value>
      <webElementGuid>51443a0a-9d1e-46bd-9e74-ab1c023b3242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
