<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Awal Bekerja_awalBekerja</name>
   <tag></tag>
   <elementGuidId>e7a2e1ab-8bbc-4f3c-9002-801281ad8d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#awalBekerja0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='awalBekerja0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67ffa5a6-8393-41e2-82b4-9de3c6d80b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c104c646-41a7-447d-a6dc-d831c74ae838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>b7117fa0-e768-4138-8b3c-e5a63220f3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>awalBekerja0</value>
      <webElementGuid>7d59d1b3-11a0-4163-9713-285857bccbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awalBekerja</value>
      <webElementGuid>9ce588e8-59b1-4559-996c-904f02568741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Masuk</value>
      <webElementGuid>e9a51367-d1dc-479c-918e-09e364a9b1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awalBekerja0&quot;)</value>
      <webElementGuid>3992aa4e-2a21-43e8-ad53-544025004633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='awalBekerja0']</value>
      <webElementGuid>f6b0d814-1abd-4e5e-bada-79684a291bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>aa78c1b7-8d09-408c-b6fb-16b6c548cbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>759f3edf-a5f5-4729-b9d3-387ef7751cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'awalBekerja0' and @name = 'awalBekerja' and @placeholder = 'Tahun Masuk']</value>
      <webElementGuid>e5b1fce1-18a0-4503-8a67-4ea52dd8256b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
