<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Akhir Bekerja_akhirBekerja</name>
   <tag></tag>
   <elementGuidId>2fbb674b-a094-4f13-96e7-2e5e04b78767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#akhirBekerja0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='akhirBekerja0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b2c7a91-1f54-4455-92b4-5534fc25ee6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a6aefa9-095c-4669-b490-7e5766b6f932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control mb-2 </value>
      <webElementGuid>0a8958e8-4b56-4c54-9d1b-57ef03287965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>akhirBekerja0</value>
      <webElementGuid>8afe3559-83a1-4c67-9ea9-d2ba7b661a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>akhirBekerja</value>
      <webElementGuid>4554f18b-55f7-4b4e-817c-9e83718a431b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Keluar</value>
      <webElementGuid>612d5476-565e-40b4-a7aa-61c98942dd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;akhirBekerja0&quot;)</value>
      <webElementGuid>744429a6-290d-454d-8fca-add13b5d9b68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='akhirBekerja0']</value>
      <webElementGuid>3f495952-6c80-4c2e-b22c-f4057c93abeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>e1d7924b-805b-4bcd-8fb3-324853a0f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>81bf3ebc-7b00-4085-aa0a-adede93cee68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'akhirBekerja0' and @name = 'akhirBekerja' and @placeholder = 'Tahun Keluar']</value>
      <webElementGuid>13240603-d512-476e-a887-d9f07bf9e820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
