<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Artikel</name>
   <tag></tag>
   <elementGuidId>117d1ef8-ba32-4fd9-bc8b-ab0636bccd56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-artikel-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-artikel-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>707bbe47-92c2-4397-bc6c-7dea4b0ba844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9ba3dab-522a-4196-ac02-5ee3fc33b2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-create border-primary artikel-background py-2 px-3 rounded-2 border-1 fw-bold</value>
      <webElementGuid>e91f879c-7f95-40d7-9c58-9fb4eebbfaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-artikel-btn</value>
      <webElementGuid>84338e96-f0eb-4e70-888f-d496ce2881d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Artikel</value>
      <webElementGuid>4c1019f2-29f0-4294-9006-02fe6148e63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-artikel-btn&quot;)</value>
      <webElementGuid>92172071-cfd6-44c8-889e-2eca90920f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-artikel-btn']</value>
      <webElementGuid>e1f1eb15-3b48-472a-9fde-d731b4ad8f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[2]/a/div/button</value>
      <webElementGuid>e2b4a57f-04cf-4288-a24d-b81eb42964ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Artikel'])[1]/following::button[1]</value>
      <webElementGuid>45afae51-532f-465a-af97-f29d58cbead5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::button[1]</value>
      <webElementGuid>42f5e2c8-a1d4-4581-a28b-fe42c0080a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'create-artikel-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>84b7179e-557c-459c-87e2-b112efa4874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/button</value>
      <webElementGuid>2dc6c769-e530-4f88-9fac-dbef0fdb0bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'create-artikel-btn' and (text() = 'Tambah Artikel' or . = 'Tambah Artikel')]</value>
      <webElementGuid>40e65a94-730d-46b0-945e-f96e6effdfe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
