<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Artikel_judul-artikel</name>
   <tag></tag>
   <elementGuidId>137e646c-b66f-40df-a9e2-6a6355875450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judul-artikel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='judul-artikel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63ff044a-98f3-4585-a371-6d064ce3b76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fad6e136-1538-4547-bcf7-e58dc0bdfc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3 border-solid border-1</value>
      <webElementGuid>d143233a-8c5d-42d3-9702-df11c5dac62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judul-artikel</value>
      <webElementGuid>2b5f88fe-05e0-4b23-afb0-19586803705a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul-artikel</value>
      <webElementGuid>47e7da01-7f68-4234-a0b0-baccbbeb905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judul-artikel&quot;)</value>
      <webElementGuid>9ada9d5a-fcf7-45b4-98c9-750fb82c92ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='judul-artikel']</value>
      <webElementGuid>8c136f24-540b-4357-a590-91e72e9103ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/input</value>
      <webElementGuid>86312653-b503-4fc3-b265-245e857c8282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Artikel'])[1]/following::input[1]</value>
      <webElementGuid>6a7c983a-de9f-454f-86f9-f1eb937bca6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::input[1]</value>
      <webElementGuid>d4cb1b56-f81b-412a-bab1-07811a003c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Artikel'])[1]/preceding::input[4]</value>
      <webElementGuid>ebb42223-fe83-4ca4-ba29-4935e01a1248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan sebagai Draft'])[1]/preceding::input[4]</value>
      <webElementGuid>ee71eea9-6df3-460a-b2fd-5920e8c9675f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59b11da2-cf1b-453c-81a6-a9da9011bc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'judul-artikel' and @name = 'judul-artikel']</value>
      <webElementGuid>3f02c92b-a252-4cb7-811c-5c7dab7e33be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
