<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Artikel_link-video-artikel</name>
   <tag></tag>
   <elementGuidId>35b56625-f542-4b46-9296-72c583d30dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-video-artikel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link-video-artikel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9531e133-fb70-478b-b8ee-44087ed52051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba4fe1f8-72fd-461f-83e6-0b151a2ea314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3 border-solid border-1</value>
      <webElementGuid>b5cee49d-6de0-46d3-a066-6fecb2df5372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-video-artikel</value>
      <webElementGuid>9734724e-1066-4e46-aae4-e231dd3a197f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link-video-artikel</value>
      <webElementGuid>6fc48dd2-f9d2-4a3b-8cb4-b1784cefa7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-video-artikel&quot;)</value>
      <webElementGuid>c92cbd2a-78df-4c14-9113-8c45f5beec17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link-video-artikel']</value>
      <webElementGuid>67275f00-5959-4eb8-bc23-d852bacf16bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/input[2]</value>
      <webElementGuid>0b9a29b7-fdde-4ac0-872f-c3b37569360e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Artikel'])[1]/following::input[3]</value>
      <webElementGuid>8808bced-e406-4d7f-a089-ef53acc1c289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::input[3]</value>
      <webElementGuid>75c2f46b-0d9a-4207-926f-683fc6953f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Artikel'])[1]/preceding::input[2]</value>
      <webElementGuid>6258d4bc-9dea-486a-8964-1354fcfe5822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan sebagai Draft'])[1]/preceding::input[2]</value>
      <webElementGuid>a25262c4-2e40-4238-9ce7-629f7b0fd530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>15c7cd7d-059b-4769-bae6-93986362f095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'link-video-artikel' and @name = 'link-video-artikel']</value>
      <webElementGuid>531de243-b9af-4b64-a1fa-6e7b688ed6a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
