<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BCA</name>
   <tag></tag>
   <elementGuidId>e69395d0-b2ef-495f-8c42-e270bd58efcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/main/div/section/div[2]/div/div/div[1]/table/tbody/tr[4]/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-decoration-none.text-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14c711ac-d621-42b9-a757-3d3d82563b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-decoration-none text-dark</value>
      <webElementGuid>c57529c8-d001-4b5e-8f40-c6a3b63a5c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dokter/transaksi/transaksi/manual/EPTG2226LOGK</value>
      <webElementGuid>d80741a1-0073-45e6-94a0-b19b8073e212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA</value>
      <webElementGuid>56721a7b-bb1b-40af-9a91-b3cbe4ff92e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height&quot;]/td[6]/a[@class=&quot;text-decoration-none text-dark&quot;]</value>
      <webElementGuid>c8e637cc-122f-458d-b870-e192d6bd1ba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/section/div[2]/div/div/div[1]/table/tbody/tr[4]/td[6]/a</value>
      <webElementGuid>50849b62-5071-4974-bf90-310a18fb0c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BCA')]</value>
      <webElementGuid>c1974c9a-1720-4ba0-b85e-ba8db5b033bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 120.000'])[1]/following::a[1]</value>
      <webElementGuid>10181f79-2ea9-4286-bc7e-6018fce553bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Instan'])[1]/following::a[1]</value>
      <webElementGuid>b9e4422f-6499-4b00-85d9-38a7b58b6824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASDI9823HUAK'])[1]/preceding::a[1]</value>
      <webElementGuid>e5e88bfa-7d7f-4c2b-acf9-ad3ead712846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orang Lain'])[1]/preceding::a[1]</value>
      <webElementGuid>2eb56eec-fac8-437c-8e8c-ad1b6e8fdd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BCA']/parent::*</value>
      <webElementGuid>d73d7fb0-bab5-4066-8ee5-a05600ac5865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dokter/transaksi/transaksi/manual/EPTG2226LOGK')]</value>
      <webElementGuid>f300e6c9-8827-4f4e-a52a-4d7ad962362f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>b8254383-74da-4936-9f9b-6ee47800d739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dokter/transaksi/transaksi/manual/EPTG2226LOGK' and (text() = 'BCA' or . = 'BCA')]</value>
      <webElementGuid>2e95306f-e940-4675-a768-7b9a64e99ba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
