<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_BCA</name>
   <tag></tag>
   <elementGuidId>dff89fa5-2db1-4440-a1ee-509085f1df9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr[3]/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>471c6b88-4e9c-454a-9ba3-1b3bab8dca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>95870bf9-8f1a-451d-baf9-43a599be8d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selectable-cell</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50ec0585-7238-4924-ab74-47274faf02df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selection-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2dcac70-3a6a-4a77-b300-7876b639c52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-editable-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>63e64f9b-5351-44be-9d15-9d36e0236285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-cell-editing</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4e23e2c-2cd5-4d46-9679-754d1941ebad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-frozen-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f3e92c0-6308-4419-a3d5-862b351f31d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>datatable</value>
      <webElementGuid>888ddc33-d78d-4c52-b9b4-20fc01498399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>514b0238-627a-47ed-bf21-9a7817fda762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA</value>
      <webElementGuid>b2d98209-f17d-4f27-87a8-7dd4d95497b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height&quot;]/td[6]</value>
      <webElementGuid>51cc399e-0ea7-491e-ba14-54ff1c3c7e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr[3]/td[6]</value>
      <webElementGuid>2795e2c7-dfe4-4a8c-94e8-83db541d8315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 120.000'])[1]/following::td[1]</value>
      <webElementGuid>11d9f2fc-1362-4198-9963-f3e110e0b18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Instan'])[2]/following::td[2]</value>
      <webElementGuid>9eaf6791-bcd0-4506-9255-845fdaa2736a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASX6737BJEU'])[1]/preceding::td[1]</value>
      <webElementGuid>5e46a8bd-d8f8-4408-b0fe-89e1d67ec549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]</value>
      <webElementGuid>27321d7c-a873-4ea2-8693-e97a3aa8b835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BCA' or . = 'BCA')]</value>
      <webElementGuid>1cb3efb0-c777-44be-a06c-c0903d59ba2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
