<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_OVO</name>
   <tag></tag>
   <elementGuidId>11966449-6837-4574-8e52-81a36fd3fd33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>685e8fed-f361-41f9-8c99-8f3ff015adca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>0090e861-b725-4b41-bd48-ff78bc06d3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selectable-cell</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09cad9fd-446e-42bb-8eb5-75ac86793d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selection-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4f6cc51-c507-4738-90ae-3ef1e6dd7b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-editable-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb87e777-4cbf-4ffc-9ace-93eec52527ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-cell-editing</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd9954ea-d9c5-4494-bb2d-bf8acd51e6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-frozen-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1a8d0f9-c17f-41ff-9b40-5599b4e5321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>datatable</value>
      <webElementGuid>b40e1c02-eda0-4533-b9f4-8fe433dbc4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>2004af8e-e303-4fd0-a80c-edf2afa3b0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OVO</value>
      <webElementGuid>937ddba7-3adc-49f5-8d8e-509e0a633763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height&quot;]/td[6]</value>
      <webElementGuid>ed2079a0-482b-4436-8d7f-2643a24f3085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr/td[6]</value>
      <webElementGuid>88ffe90b-e6a9-4f4e-bedd-36446a181f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 200.000'])[1]/following::td[1]</value>
      <webElementGuid>dc82af7b-4225-42ab-949a-b03258abb76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Premium'])[1]/following::td[2]</value>
      <webElementGuid>5e0c52e9-44db-4e9e-9f6a-e9b450ed9ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TLFY0399HJIU'])[1]/preceding::td[1]</value>
      <webElementGuid>4a243701-e4fa-4ae2-9a91-565753b0f593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>30eae7cf-b72a-4298-aa7b-fadbaf7df21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'OVO' or . = 'OVO')]</value>
      <webElementGuid>3d256303-a7c1-4f14-8cdb-df45bb1b958d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
