<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Paket Instan</name>
   <tag></tag>
   <elementGuidId>4c7ea345-8a26-41e3-9931-37319396675e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/main/div/section/div[2]/div/div/div[1]/table/tbody/tr[4]/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>66ce2392-dbce-4682-8b41-7327698e179c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>2e3e3b7a-c84f-49db-829d-b66d72cdef85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selectable-cell</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4cad6b14-aa6c-401e-bb08-b29a7f479614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selection-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8cbbfa25-5f28-4786-802d-66d8d465f743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-editable-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac1b9b34-177f-47d3-85ea-a287e3fdd8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-cell-editing</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1ed544a-2c87-42cb-8d6d-5fb021d1abf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-frozen-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1637d42-f20d-4cd7-b6cf-e9ea228da862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>datatable</value>
      <webElementGuid>26970529-8738-45d2-9cb7-846654a4f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>c9e02861-04c0-4891-8bf1-7be1299c80ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paket Instan</value>
      <webElementGuid>7ac41973-8083-46ad-bbf4-3de65a3b4eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height&quot;]/td[4]</value>
      <webElementGuid>e314e615-3bcd-48b4-83b8-42f197cae13f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/section/div[2]/div/div/div[1]/table/tbody/tr[4]/td[4]/span</value>
      <webElementGuid>d7adc328-6510-4d88-93ca-f34d2b76aa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gwenchanayo'])[1]/following::td[2]</value>
      <webElementGuid>ab71b459-5a22-49a3-8c6b-193835a2212a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TLFY0399HJIU'])[1]/following::td[3]</value>
      <webElementGuid>1b2ab982-127c-4566-ac64-3aa2476a7efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 100.000'])[1]/preceding::td[1]</value>
      <webElementGuid>e6cc24c0-5cf9-4aea-9aa8-20461478baa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOPAY'])[1]/preceding::td[2]</value>
      <webElementGuid>5b7aeccb-e98e-4e24-a45a-6c6fffe43867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Paket Instan']/parent::*</value>
      <webElementGuid>0a21bfb4-3ad9-4b0f-9a24-a8a2619b1f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>77f100a7-ac9e-4923-b04f-5bb694066bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Paket Instan' or . = 'Paket Instan')]</value>
      <webElementGuid>b011d945-c43d-42f4-956b-c3cb3d7ba218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
