<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Rp 120.000</name>
   <tag></tag>
   <elementGuidId>71b71753-56bc-4366-a5cb-055ec9aee4a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>05f3528d-f886-4fe1-9d76-c0505dfc76c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>c3e2b871-b075-4209-a777-7dfdb8e43683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selectable-cell</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ca089fe-856f-4a3f-8597-568203c1b4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selection-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f07bb37e-3631-480c-8b72-0d7ab3ef4f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-editable-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a14a81f3-e4ae-4acd-9ed7-ac9315c8cb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-cell-editing</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68102e2f-f6fb-4c2e-b2bd-42ce903fd8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-frozen-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52c529cf-6c7d-4696-8c94-3b7b295bc6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>datatable</value>
      <webElementGuid>d7d8f0d0-8729-4263-aa97-8da7e4819668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>69222cb8-f50f-4b0f-b952-b9c77bdc8a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 120.000</value>
      <webElementGuid>24975101-aad4-4479-953c-f6f725b3fa66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;p-3&quot;]/section[@class=&quot;section-transaksi&quot;]/div[@class=&quot;row table-transaksi&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-datatable-sm p-datatable p-component p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;table-row-height&quot;]/td[5]</value>
      <webElementGuid>880aef21-51af-4704-b273-1adf5dd329e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div[2]/div/div/div/table/tbody/tr/td[5]</value>
      <webElementGuid>6933b2c0-2259-46e7-b552-e1407275658c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Instan'])[1]/following::td[1]</value>
      <webElementGuid>37b2d6f9-837e-466d-b015-b12075de00f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gwenchanaaa'])[1]/following::td[3]</value>
      <webElementGuid>a768943c-4999-4c4f-9014-16f2e62713bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA'])[1]/preceding::td[1]</value>
      <webElementGuid>4e607054-95ca-4a39-9b7e-68f719fc4355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp 120.000']/parent::*</value>
      <webElementGuid>4817717c-b795-4f7c-8c03-e686c9b22ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>9ef32d3d-a793-4e10-ab56-8c59205d7554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Rp 120.000' or . = 'Rp 120.000')]</value>
      <webElementGuid>0abc8198-b9af-4dea-aa74-6ecb37da1e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
