<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mengatasi Stress</name>
   <tag></tag>
   <elementGuidId>f427d436-3baf-4833-8bd2-245b58d8b524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > button.btn.btn-outline-primary.text-black.fw-semibold.rounded-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0e78651-2048-4e85-88b0-cf70ccb4a5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23782ccd-f75e-4daa-af33-a37668672bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary text-black fw-semibold rounded-5</value>
      <webElementGuid>9ea4dc14-16ae-4882-a395-7ba4ed98b21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mengatasi Stress</value>
      <webElementGuid>3df5c901-70ed-461b-a124-d84595fa165b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;body__chatbot d-flex justify-content-center my-5&quot;]/div[@class=&quot;wrapper__chatbot d-flex flex-column justify-content-between&quot;]/div[@class=&quot;chat__bot p-3&quot;]/div[@class=&quot;chat-text d-flex align-items-center m-0 p-0 flex-row gap-2 d-block aos-init aos-animate&quot;]/div[2]/button[@class=&quot;btn btn-outline-primary text-black fw-semibold rounded-5&quot;]</value>
      <webElementGuid>3c5ac21e-03f2-4ae3-bb31-9cbd8c48ebcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[3]</value>
      <webElementGuid>d92fcc43-4773-4b47-b6bf-02721adaf29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/div[2]/button</value>
      <webElementGuid>68efe966-9dfc-40fa-bb5d-8bd5b97d85f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengatasi Gangguan Kecemasan'])[1]/following::button[1]</value>
      <webElementGuid>ef6a1a4f-27c1-4eea-945c-6336c50834f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Bot'])[1]/following::button[2]</value>
      <webElementGuid>d5cef115-e580-4944-b5ed-5e9780d3fe15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengatasi Depresi'])[1]/preceding::button[1]</value>
      <webElementGuid>591d0711-182c-4649-9e21-1b1c0131e3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengatasi Kegilaan'])[1]/preceding::button[2]</value>
      <webElementGuid>90ae21af-541d-4d95-a33e-255515d2ed89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mengatasi Stress']/parent::*</value>
      <webElementGuid>9466afee-d433-4616-9958-5c5ee9fe3567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8ffcf07f-dc09-43b9-86ac-2a61dc199ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Mengatasi Stress' or . = 'Mengatasi Stress')]</value>
      <webElementGuid>02b84e82-b2a7-400a-8da9-b7ac445346c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
