<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_via_notif-icon</name>
   <tag></tag>
   <elementGuidId>dbdaf33e-6cbd-4375-8fec-61a63260cefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.notif-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93bf004d-290a-4407-a6b3-06d1bc260384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/notifications-ca6ac4fa.svg</value>
      <webElementGuid>55989e19-9a67-4690-9f52-02c80a5a2502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dropdown Image</value>
      <webElementGuid>35192f48-00df-40de-abeb-45de39814db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif-icon</value>
      <webElementGuid>313f0112-3bf6-4abc-81c1-8ed85eedbfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;d-flex align-items-center gap-2 pe-4&quot;]/div[@class=&quot;dropdown&quot;]/button[@class=&quot;nav-link dropdown-toggle custom-dropdown-toggle show&quot;]/img[@class=&quot;notif-icon&quot;]</value>
      <webElementGuid>d35f1298-21c9-4d8e-96c4-4786334eb0b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/div/div/button/img</value>
      <webElementGuid>6fca7733-f43b-4588-940a-0690e293a2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dropdown Image']</value>
      <webElementGuid>b348f75f-9e45-4124-bbc3-434c65e4323f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>731a846f-1a2f-47f2-9dd1-2f2b8e21e65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/notifications-ca6ac4fa.svg' and @alt = 'Dropdown Image']</value>
      <webElementGuid>1efd1e7d-f271-498d-bbe2-a050e6383ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
