<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s your mood)_message</name>
   <tag></tag>
   <elementGuidId>9271ac67-d7f3-45cb-afc5-833b6d0b5935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;message&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9629c0a0-b9db-4b62-975e-ffc3715fb4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9b38bd6-ef63-4770-b5b7-e08b623c44b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control shadow-none border-secondary-subtle</value>
      <webElementGuid>4f82b69a-2aed-4d92-a530-78cdf7745274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>bfc4125d-a4a6-42d8-bc9f-274f7d315a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik pesan</value>
      <webElementGuid>6b8fd3f9-a75b-4d7b-82ca-fb4ea57aa0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;body__chatbot d-flex justify-content-center my-5&quot;]/div[@class=&quot;wrapper__chatbot d-flex flex-column justify-content-between&quot;]/form[@class=&quot;input__chatbot bg-white d-flex py-2&quot;]/input[@class=&quot;form-control shadow-none border-secondary-subtle&quot;]</value>
      <webElementGuid>3e2367b0-bb8b-48df-968e-ce499368c278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='message']</value>
      <webElementGuid>559ba186-7f07-4cbb-922e-d43e698c8e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/input</value>
      <webElementGuid>3cefc076-882f-4cac-ba09-f14c70240860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>b864e19d-b925-4778-a2f1-5706af2d4b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'message' and @placeholder = 'Ketik pesan']</value>
      <webElementGuid>b56b008d-1ebe-4927-af1a-35ba4887b9fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
